
 SCAN
 ______________________________________

 Datum:                18.03.2015
 Zeit:                 15:32:57
 Methode:              PKA
 Ordinaten Modus:      A
 Scan Bereich:          250.0  -  700.0  nm
 Intervall:              1.00  nm
 Spalt:                  2.00  nm
 Scan-Geschwindigkeit:  240.0  nm/min
 Benutzer:
 ______________________________________

 Proben ID
 ______________________________________

 pH1a
 pH1b

